# Generated by Django 5.1.4 on 2024-12-20 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_alter_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='user',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='password',
            new_name='Users_password',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='role',
            new_name='Users_role',
        ),
        migrations.AlterField(
            model_name='club',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='clubcommittee',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='ClubAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement', models.TextField()),
                ('date_awarded', models.DateField()),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.admin')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.club')),
            ],
            options={
                'db_table': 'ClubAchievements',
            },
        ),
        migrations.CreateModel(
            name='ClubMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.club')),
                ('committee', models.ForeignKey(blank=True, db_column='Club_member_committee', null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_app.clubcommittee')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.user')),
            ],
            options={
                'db_table': 'ClubMembers',
            },
        ),
        migrations.CreateModel(
            name='Collaboration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, db_column='collaboration_description', null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], db_column='collaboration_status', default='Pending', max_length=20)),
                ('application_date', models.DateField(blank=True, null=True)),
                ('applying_admin', models.ForeignKey(db_column='applying_admin_id', on_delete=django.db.models.deletion.CASCADE, related_name='applied_admin', to='my_app.admin')),
                ('applying_club', models.ForeignKey(db_column='applying_club_id', on_delete=django.db.models.deletion.CASCADE, related_name='applied_club', to='my_app.club')),
                ('receiving_admin', models.ForeignKey(db_column='receiving_admin_id', on_delete=django.db.models.deletion.CASCADE, related_name='received_admin', to='my_app.admin')),
                ('receiving_club', models.ForeignKey(db_column='receiving_club_id', on_delete=django.db.models.deletion.CASCADE, related_name='received_club', to='my_app.club')),
            ],
            options={
                'db_table': 'Collaboration',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('club_name', models.CharField(max_length=255)),
                ('event_name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, db_column='Events_description', null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('staff_list', models.TextField(blank=True, null=True)),
                ('sponsors', models.TextField(blank=True, null=True)),
                ('event_date', models.DateField(blank=True, db_column='Events_date', null=True)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_app.admin')),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_app.club')),
            ],
            options={
                'db_table': 'Events',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('track_sessions', models.AutoField(primary_key=True, serialize=False)),
                ('club_name', models.CharField(max_length=255)),
                ('schedule', models.TextField(blank=True, db_column='Sessions_schedule', null=True)),
                ('attendance_count', models.IntegerField(blank=True, null=True)),
                ('material_file', models.CharField(blank=True, max_length=255, null=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.admin')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.club')),
                ('instructor', models.ForeignKey(blank=True, db_column='instructor_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_app.user')),
            ],
            options={
                'db_table': 'Sessions',
            },
        ),
    ]
