name: Python CI/CD for SW Project Mohamed

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: ClubManagementSystem
          MYSQL_ROOT_PASSWORD: don895sk
        ports: 
        - 3306:3306
      options: >-
        --health-cmd="mysqladmin ping -h localhost " -u root -p<don895sk>"
        --health-interval=10s
        --health-timeout=5s
        --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set DJANGO_SETTINGS_MODULE environment variable
        run: echo "DJANGO_SETTINGS_MODULE=my_project.settings" >> $GITHUB_ENV  # Correct module path

      - name: Run Django tests
        run: |
          python manage.py test  # Run Django tests
