name: Python CI/CD for SW Project Mohamed

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r my_project/requirements.txt  # Update this line if your requirements.txt is in a subfolder

      - name: Run Django migrations (if applicable)
        run: |
          python manage.py migrate

      - name: Run tests
        run: |
          python manage.py test

      - name: Collect static files (if applicable)
        run: |
          python manage.py collectstatic --noinput

      - name: Run Python script (if needed)
        run: |
          python hello.py

      - name: Deploy to production (if applicable)
        if: github.ref == 'refs/heads/main'
        run: |
          echo "Deploying to production..."
